#!/usr/bin/env bash
# Install git hooks for this repo.
# Run once after cloning: bash scripts/ci/install-hooks.sh
set -euo pipefail

HOOK_FILE=".git/hooks/pre-commit"

cat > "$HOOK_FILE" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/ci/install-hooks.sh
# Blocks commits containing raw wallet addresses.
set -e
python3 scripts/ci/check_addresses.py
HOOK

chmod +x "$HOOK_FILE"
echo "Installed pre-commit hook at $HOOK_FILE"
echo ""
echo "Test with:"
echo "  echo 'addr: So11111111111111111111111111111111111111113' > /tmp/test.txt"
echo "  git add -f /tmp/test.txt  # won't work outside repo, this is just an example"
